/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package axTLSj;

public class axtlsjJNI {
  public final static native int ssl_read(int jarg1, Object jarg2);
  public final static native int getFd(Object jarg1);
  public final static native int SSL_SESSION_ID_SIZE_get();
  public final static native int SSL_CLIENT_AUTHENTICATION_get();
  public final static native int SSL_SERVER_VERIFY_LATER_get();
  public final static native int SSL_NO_DEFAULT_KEY_get();
  public final static native int SSL_DISPLAY_STATES_get();
  public final static native int SSL_DISPLAY_BYTES_get();
  public final static native int SSL_DISPLAY_CERTS_get();
  public final static native int SSL_DISPLAY_RSA_get();
  public final static native int SSL_CONNECT_IN_PARTS_get();
  public final static native int SSL_OK_get();
  public final static native int SSL_NOT_OK_get();
  public final static native int SSL_ERROR_DEAD_get();
  public final static native int SSL_CLOSE_NOTIFY_get();
  public final static native int SSL_ERROR_CONN_LOST_get();
  public final static native int SSL_ERROR_RECORD_OVERFLOW_get();
  public final static native int SSL_ERROR_SOCK_SETUP_FAILURE_get();
  public final static native int SSL_ERROR_INVALID_HANDSHAKE_get();
  public final static native int SSL_ERROR_INVALID_PROT_MSG_get();
  public final static native int SSL_ERROR_INVALID_HMAC_get();
  public final static native int SSL_ERROR_INVALID_VERSION_get();
  public final static native int SSL_ERROR_UNSUPPORTED_EXTENSION_get();
  public final static native int SSL_ERROR_INVALID_SESSION_get();
  public final static native int SSL_ERROR_NO_CIPHER_get();
  public final static native int SSL_ERROR_INVALID_CERT_HASH_ALG_get();
  public final static native int SSL_ERROR_BAD_CERTIFICATE_get();
  public final static native int SSL_ERROR_INVALID_KEY_get();
  public final static native int SSL_ERROR_FINISHED_INVALID_get();
  public final static native int SSL_ERROR_NO_CERT_DEFINED_get();
  public final static native int SSL_ERROR_NO_CLIENT_RENOG_get();
  public final static native int SSL_ERROR_NOT_SUPPORTED_get();
  public final static native int SSL_X509_OFFSET_get();
  public final static native int SSL_ALERT_TYPE_WARNING_get();
  public final static native int SLL_ALERT_TYPE_FATAL_get();
  public final static native int SSL_ALERT_CLOSE_NOTIFY_get();
  public final static native int SSL_ALERT_UNEXPECTED_MESSAGE_get();
  public final static native int SSL_ALERT_BAD_RECORD_MAC_get();
  public final static native int SSL_ALERT_RECORD_OVERFLOW_get();
  public final static native int SSL_ALERT_HANDSHAKE_FAILURE_get();
  public final static native int SSL_ALERT_BAD_CERTIFICATE_get();
  public final static native int SSL_ALERT_UNSUPPORTED_CERTIFICATE_get();
  public final static native int SSL_ALERT_CERTIFICATE_EXPIRED_get();
  public final static native int SSL_ALERT_CERTIFICATE_UNKNOWN_get();
  public final static native int SSL_ALERT_ILLEGAL_PARAMETER_get();
  public final static native int SSL_ALERT_UNKNOWN_CA_get();
  public final static native int SSL_ALERT_DECODE_ERROR_get();
  public final static native int SSL_ALERT_DECRYPT_ERROR_get();
  public final static native int SSL_ALERT_INVALID_VERSION_get();
  public final static native int SSL_ALERT_NO_RENEGOTIATION_get();
  public final static native int SSL_ALERT_UNSUPPORTED_EXTENSION_get();
  public final static native int SSL_AES128_SHA_get();
  public final static native int SSL_AES256_SHA_get();
  public final static native int SSL_AES128_SHA256_get();
  public final static native int SSL_AES256_SHA256_get();
  public final static native int SSL_BUILD_SKELETON_MODE_get();
  public final static native int SSL_BUILD_SERVER_ONLY_get();
  public final static native int SSL_BUILD_ENABLE_VERIFICATION_get();
  public final static native int SSL_BUILD_ENABLE_CLIENT_get();
  public final static native int SSL_BUILD_FULL_MODE_get();
  public final static native int SSL_BUILD_MODE_get();
  public final static native int SSL_MAX_CERT_CFG_OFFSET_get();
  public final static native int SSL_MAX_CA_CERT_CFG_OFFSET_get();
  public final static native int SSL_HAS_PEM_get();
  public final static native int SSL_DEFAULT_SVR_SESS_get();
  public final static native int SSL_DEFAULT_CLNT_SESS_get();
  public final static native int SSL_X509_CERT_COMMON_NAME_get();
  public final static native int SSL_X509_CERT_ORGANIZATION_get();
  public final static native int SSL_X509_CERT_ORGANIZATIONAL_NAME_get();
  public final static native int SSL_X509_CERT_LOCATION_get();
  public final static native int SSL_X509_CERT_COUNTRY_get();
  public final static native int SSL_X509_CERT_STATE_get();
  public final static native int SSL_X509_CA_CERT_COMMON_NAME_get();
  public final static native int SSL_X509_CA_CERT_ORGANIZATION_get();
  public final static native int SSL_X509_CA_CERT_ORGANIZATIONAL_NAME_get();
  public final static native int SSL_X509_CA_CERT_LOCATION_get();
  public final static native int SSL_X509_CA_CERT_COUNTRY_get();
  public final static native int SSL_X509_CA_CERT_STATE_get();
  public final static native int SSL_OBJ_X509_CERT_get();
  public final static native int SSL_OBJ_X509_CACERT_get();
  public final static native int SSL_OBJ_RSA_KEY_get();
  public final static native int SSL_OBJ_PKCS8_get();
  public final static native int SSL_OBJ_PKCS12_get();
  public final static native int ssl_ctx_new(int jarg1, int jarg2);
  public final static native void ssl_ctx_free(int jarg1);
  public final static native long ssl_ext_new();
  public final static native void ssl_ext_free(long jarg1);
  public final static native int ssl_server_new(int jarg1, int jarg2);
  public final static native int ssl_client_new(int jarg1, int jarg2, byte[] jarg3, byte jarg4, long jarg5);
  public final static native void ssl_free(int jarg1);
  public final static native int ssl_write(int jarg1, byte[] jarg2, int jarg3);
  public final static native int ssl_find(int jarg1, int jarg2);
  public final static native byte[] ssl_get_session_id(int jarg1);
  public final static native byte ssl_get_session_id_size(int jarg1);
  public final static native byte ssl_get_cipher_id(int jarg1);
  public final static native int ssl_handshake_status(int jarg1);
  public final static native int ssl_get_config(int jarg1);
  public final static native void ssl_display_error(int jarg1);
  public final static native int ssl_verify_cert(int jarg1);
  public final static native String ssl_get_cert_dn(int jarg1, int jarg2);
  public final static native String ssl_get_cert_subject_alt_dnsname(int jarg1, int jarg2);
  public final static native int ssl_renegotiate(int jarg1);
  public final static native int ssl_obj_load(int jarg1, int jarg2, String jarg3, String jarg4);
  public final static native int ssl_obj_memory_load(int jarg1, int jarg2, byte[] jarg3, int jarg4, String jarg5);
  public final static native String ssl_version();
}
