# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.8
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

package axtlsp;
use base qw(Exporter);
use base qw(DynaLoader);
package axtlspc;
bootstrap axtlsp;
package axtlsp;
@EXPORT = qw();

# ---------- BASE METHODS -------------

package axtlsp;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package axtlsp;

*ssl_ctx_new = *axtlspc::ssl_ctx_new;
*ssl_ctx_free = *axtlspc::ssl_ctx_free;
*ssl_ext_new = *axtlspc::ssl_ext_new;
*ssl_ext_free = *axtlspc::ssl_ext_free;
*ssl_server_new = *axtlspc::ssl_server_new;
*ssl_client_new = *axtlspc::ssl_client_new;
*ssl_free = *axtlspc::ssl_free;
*ssl_read = *axtlspc::ssl_read;
*ssl_write = *axtlspc::ssl_write;
*ssl_find = *axtlspc::ssl_find;
*ssl_get_session_id = *axtlspc::ssl_get_session_id;
*ssl_get_session_id_size = *axtlspc::ssl_get_session_id_size;
*ssl_get_cipher_id = *axtlspc::ssl_get_cipher_id;
*ssl_handshake_status = *axtlspc::ssl_handshake_status;
*ssl_get_config = *axtlspc::ssl_get_config;
*ssl_display_error = *axtlspc::ssl_display_error;
*ssl_verify_cert = *axtlspc::ssl_verify_cert;
*ssl_get_cert_dn = *axtlspc::ssl_get_cert_dn;
*ssl_get_cert_subject_alt_dnsname = *axtlspc::ssl_get_cert_subject_alt_dnsname;
*ssl_renegotiate = *axtlspc::ssl_renegotiate;
*ssl_obj_load = *axtlspc::ssl_obj_load;
*ssl_obj_memory_load = *axtlspc::ssl_obj_memory_load;
*ssl_version = *axtlspc::ssl_version;

# ------- VARIABLE STUBS --------

package axtlsp;

*SSL_SESSION_ID_SIZE = *axtlspc::SSL_SESSION_ID_SIZE;
*SSL_CLIENT_AUTHENTICATION = *axtlspc::SSL_CLIENT_AUTHENTICATION;
*SSL_SERVER_VERIFY_LATER = *axtlspc::SSL_SERVER_VERIFY_LATER;
*SSL_NO_DEFAULT_KEY = *axtlspc::SSL_NO_DEFAULT_KEY;
*SSL_DISPLAY_STATES = *axtlspc::SSL_DISPLAY_STATES;
*SSL_DISPLAY_BYTES = *axtlspc::SSL_DISPLAY_BYTES;
*SSL_DISPLAY_CERTS = *axtlspc::SSL_DISPLAY_CERTS;
*SSL_DISPLAY_RSA = *axtlspc::SSL_DISPLAY_RSA;
*SSL_CONNECT_IN_PARTS = *axtlspc::SSL_CONNECT_IN_PARTS;
*SSL_OK = *axtlspc::SSL_OK;
*SSL_NOT_OK = *axtlspc::SSL_NOT_OK;
*SSL_ERROR_DEAD = *axtlspc::SSL_ERROR_DEAD;
*SSL_CLOSE_NOTIFY = *axtlspc::SSL_CLOSE_NOTIFY;
*SSL_ERROR_CONN_LOST = *axtlspc::SSL_ERROR_CONN_LOST;
*SSL_ERROR_RECORD_OVERFLOW = *axtlspc::SSL_ERROR_RECORD_OVERFLOW;
*SSL_ERROR_SOCK_SETUP_FAILURE = *axtlspc::SSL_ERROR_SOCK_SETUP_FAILURE;
*SSL_ERROR_INVALID_HANDSHAKE = *axtlspc::SSL_ERROR_INVALID_HANDSHAKE;
*SSL_ERROR_INVALID_PROT_MSG = *axtlspc::SSL_ERROR_INVALID_PROT_MSG;
*SSL_ERROR_INVALID_HMAC = *axtlspc::SSL_ERROR_INVALID_HMAC;
*SSL_ERROR_INVALID_VERSION = *axtlspc::SSL_ERROR_INVALID_VERSION;
*SSL_ERROR_UNSUPPORTED_EXTENSION = *axtlspc::SSL_ERROR_UNSUPPORTED_EXTENSION;
*SSL_ERROR_INVALID_SESSION = *axtlspc::SSL_ERROR_INVALID_SESSION;
*SSL_ERROR_NO_CIPHER = *axtlspc::SSL_ERROR_NO_CIPHER;
*SSL_ERROR_INVALID_CERT_HASH_ALG = *axtlspc::SSL_ERROR_INVALID_CERT_HASH_ALG;
*SSL_ERROR_BAD_CERTIFICATE = *axtlspc::SSL_ERROR_BAD_CERTIFICATE;
*SSL_ERROR_INVALID_KEY = *axtlspc::SSL_ERROR_INVALID_KEY;
*SSL_ERROR_FINISHED_INVALID = *axtlspc::SSL_ERROR_FINISHED_INVALID;
*SSL_ERROR_NO_CERT_DEFINED = *axtlspc::SSL_ERROR_NO_CERT_DEFINED;
*SSL_ERROR_NO_CLIENT_RENOG = *axtlspc::SSL_ERROR_NO_CLIENT_RENOG;
*SSL_ERROR_NOT_SUPPORTED = *axtlspc::SSL_ERROR_NOT_SUPPORTED;
*SSL_X509_OFFSET = *axtlspc::SSL_X509_OFFSET;
*SSL_ALERT_TYPE_WARNING = *axtlspc::SSL_ALERT_TYPE_WARNING;
*SLL_ALERT_TYPE_FATAL = *axtlspc::SLL_ALERT_TYPE_FATAL;
*SSL_ALERT_CLOSE_NOTIFY = *axtlspc::SSL_ALERT_CLOSE_NOTIFY;
*SSL_ALERT_UNEXPECTED_MESSAGE = *axtlspc::SSL_ALERT_UNEXPECTED_MESSAGE;
*SSL_ALERT_BAD_RECORD_MAC = *axtlspc::SSL_ALERT_BAD_RECORD_MAC;
*SSL_ALERT_RECORD_OVERFLOW = *axtlspc::SSL_ALERT_RECORD_OVERFLOW;
*SSL_ALERT_HANDSHAKE_FAILURE = *axtlspc::SSL_ALERT_HANDSHAKE_FAILURE;
*SSL_ALERT_BAD_CERTIFICATE = *axtlspc::SSL_ALERT_BAD_CERTIFICATE;
*SSL_ALERT_UNSUPPORTED_CERTIFICATE = *axtlspc::SSL_ALERT_UNSUPPORTED_CERTIFICATE;
*SSL_ALERT_CERTIFICATE_EXPIRED = *axtlspc::SSL_ALERT_CERTIFICATE_EXPIRED;
*SSL_ALERT_CERTIFICATE_UNKNOWN = *axtlspc::SSL_ALERT_CERTIFICATE_UNKNOWN;
*SSL_ALERT_ILLEGAL_PARAMETER = *axtlspc::SSL_ALERT_ILLEGAL_PARAMETER;
*SSL_ALERT_UNKNOWN_CA = *axtlspc::SSL_ALERT_UNKNOWN_CA;
*SSL_ALERT_DECODE_ERROR = *axtlspc::SSL_ALERT_DECODE_ERROR;
*SSL_ALERT_DECRYPT_ERROR = *axtlspc::SSL_ALERT_DECRYPT_ERROR;
*SSL_ALERT_INVALID_VERSION = *axtlspc::SSL_ALERT_INVALID_VERSION;
*SSL_ALERT_NO_RENEGOTIATION = *axtlspc::SSL_ALERT_NO_RENEGOTIATION;
*SSL_ALERT_UNSUPPORTED_EXTENSION = *axtlspc::SSL_ALERT_UNSUPPORTED_EXTENSION;
*SSL_AES128_SHA = *axtlspc::SSL_AES128_SHA;
*SSL_AES256_SHA = *axtlspc::SSL_AES256_SHA;
*SSL_AES128_SHA256 = *axtlspc::SSL_AES128_SHA256;
*SSL_AES256_SHA256 = *axtlspc::SSL_AES256_SHA256;
*SSL_BUILD_SKELETON_MODE = *axtlspc::SSL_BUILD_SKELETON_MODE;
*SSL_BUILD_SERVER_ONLY = *axtlspc::SSL_BUILD_SERVER_ONLY;
*SSL_BUILD_ENABLE_VERIFICATION = *axtlspc::SSL_BUILD_ENABLE_VERIFICATION;
*SSL_BUILD_ENABLE_CLIENT = *axtlspc::SSL_BUILD_ENABLE_CLIENT;
*SSL_BUILD_FULL_MODE = *axtlspc::SSL_BUILD_FULL_MODE;
*SSL_BUILD_MODE = *axtlspc::SSL_BUILD_MODE;
*SSL_MAX_CERT_CFG_OFFSET = *axtlspc::SSL_MAX_CERT_CFG_OFFSET;
*SSL_MAX_CA_CERT_CFG_OFFSET = *axtlspc::SSL_MAX_CA_CERT_CFG_OFFSET;
*SSL_HAS_PEM = *axtlspc::SSL_HAS_PEM;
*SSL_DEFAULT_SVR_SESS = *axtlspc::SSL_DEFAULT_SVR_SESS;
*SSL_DEFAULT_CLNT_SESS = *axtlspc::SSL_DEFAULT_CLNT_SESS;
*SSL_X509_CERT_COMMON_NAME = *axtlspc::SSL_X509_CERT_COMMON_NAME;
*SSL_X509_CERT_ORGANIZATION = *axtlspc::SSL_X509_CERT_ORGANIZATION;
*SSL_X509_CERT_ORGANIZATIONAL_NAME = *axtlspc::SSL_X509_CERT_ORGANIZATIONAL_NAME;
*SSL_X509_CERT_LOCATION = *axtlspc::SSL_X509_CERT_LOCATION;
*SSL_X509_CERT_COUNTRY = *axtlspc::SSL_X509_CERT_COUNTRY;
*SSL_X509_CERT_STATE = *axtlspc::SSL_X509_CERT_STATE;
*SSL_X509_CA_CERT_COMMON_NAME = *axtlspc::SSL_X509_CA_CERT_COMMON_NAME;
*SSL_X509_CA_CERT_ORGANIZATION = *axtlspc::SSL_X509_CA_CERT_ORGANIZATION;
*SSL_X509_CA_CERT_ORGANIZATIONAL_NAME = *axtlspc::SSL_X509_CA_CERT_ORGANIZATIONAL_NAME;
*SSL_X509_CA_CERT_LOCATION = *axtlspc::SSL_X509_CA_CERT_LOCATION;
*SSL_X509_CA_CERT_COUNTRY = *axtlspc::SSL_X509_CA_CERT_COUNTRY;
*SSL_X509_CA_CERT_STATE = *axtlspc::SSL_X509_CA_CERT_STATE;
*SSL_OBJ_X509_CERT = *axtlspc::SSL_OBJ_X509_CERT;
*SSL_OBJ_X509_CACERT = *axtlspc::SSL_OBJ_X509_CACERT;
*SSL_OBJ_RSA_KEY = *axtlspc::SSL_OBJ_RSA_KEY;
*SSL_OBJ_PKCS8 = *axtlspc::SSL_OBJ_PKCS8;
*SSL_OBJ_PKCS12 = *axtlspc::SSL_OBJ_PKCS12;
1;
